#!/usr/bin/env bash
# gen-types.sh — Supabase DB 스키마에서 TypeScript 타입 자동 생성
#
# 사용법:
#   bash scripts/gen-types.sh            # 변경 시에만 업데이트
#   bash scripts/gen-types.sh --force    # 강제 재생성

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# .env에서 토큰 로드
if [ -f .env ]; then
  export $(grep -v '^#' .env | grep -v '^\s*$' | xargs)
fi

if [ -z "${SUPABASE_ACCESS_TOKEN:-}" ]; then
  echo "❌ SUPABASE_ACCESS_TOKEN이 설정되지 않았습니다."
  echo "   .env 파일을 확인하세요."
  exit 1
fi

FORCE=false
[ "${1:-}" = "--force" ] && FORCE=true

OUTPUT_FILE="$ROOT/src/types/database.gen.ts"

echo "=== Supabase 타입 생성 ==="

TMPFILE="$(mktemp)"
trap 'rm -f "$TMPFILE" "$TMPFILE.full"' EXIT

npx supabase gen types typescript --linked --schema public > "$TMPFILE"

if ! grep -q 'export type Database' "$TMPFILE"; then
  echo "❌ 생성된 타입에 'export type Database'가 없습니다."
  echo "   Supabase 연결 상태를 확인하세요."
  exit 1
fi

{
  echo "// This file is auto-generated by scripts/gen-types.sh"
  echo "// Do not edit manually. Run 'bash scripts/gen-types.sh' to regenerate."
  echo "// Generated at: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo ""
  cat "$TMPFILE"
} > "$TMPFILE.full"

if [ -f "$OUTPUT_FILE" ] && ! $FORCE; then
  OLD_CONTENT="$(tail -n +4 "$OUTPUT_FILE")"
  NEW_CONTENT="$(tail -n +4 "$TMPFILE.full")"

  if [ "$OLD_CONTENT" = "$NEW_CONTENT" ]; then
    echo "✅ 스키마 변경 없음 — 타입 파일 유지"
    exit 0
  fi
fi

cp "$TMPFILE.full" "$OUTPUT_FILE"

LINES=$(wc -l < "$OUTPUT_FILE")
echo "✅ 타입 생성 완료: $OUTPUT_FILE ($LINES 줄)"
